// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiYHn5pLMm420LTEh-H72kKNORxvs0RHo',
    appId: '1:583682512061:web:314e9093eb68cd8aef93d4',
    messagingSenderId: '583682512061',
    projectId: 'dsoc-pos-app',
    authDomain: 'dsoc-pos-app.firebaseapp.com',
    databaseURL: 'https://dsoc-pos-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dsoc-pos-app.appspot.com',
    measurementId: 'G-QL22E02QQX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpTQgnrUcrRUnBNlbGgAqhFQW0VfTcaG0',
    appId: '1:583682512061:android:ca26a8f0c664b306ef93d4',
    messagingSenderId: '583682512061',
    projectId: 'dsoc-pos-app',
    databaseURL: 'https://dsoc-pos-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dsoc-pos-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1hBWGUmq0yz1yO_4goh4EbucQ3SgZqWs',
    appId: '1:583682512061:ios:5bd6b0e6137d3ac9ef93d4',
    messagingSenderId: '583682512061',
    projectId: 'dsoc-pos-app',
    databaseURL: 'https://dsoc-pos-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dsoc-pos-app.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1hBWGUmq0yz1yO_4goh4EbucQ3SgZqWs',
    appId: '1:583682512061:ios:5bd6b0e6137d3ac9ef93d4',
    messagingSenderId: '583682512061',
    projectId: 'dsoc-pos-app',
    databaseURL: 'https://dsoc-pos-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dsoc-pos-app.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiYHn5pLMm420LTEh-H72kKNORxvs0RHo',
    appId: '1:583682512061:web:6871458b4886069eef93d4',
    messagingSenderId: '583682512061',
    projectId: 'dsoc-pos-app',
    authDomain: 'dsoc-pos-app.firebaseapp.com',
    databaseURL: 'https://dsoc-pos-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dsoc-pos-app.appspot.com',
    measurementId: 'G-RNBQMYXE7F',
  );

}